```{r preparation, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
versionid <- "QXXXXXXXXX_US.Rmd"
prm <- teachR::questions_set_parameters(versionid, test_parameters, as_latex, record_version)
base::set.seed(prm$seed)

answer_group <- feedbacks |>
  dplyr::filter(code == "QXXXXXXXXX", language == "US") |>
  dplyr::select(item, keywords)
answer_group <- base::split(answer_group, f = answer_group$keywords)

situations <- base::list(
  situation1 = base::list(
    interrogation = "Which of the following alternatives are associated to the first keyword?",
    correct = answer_group$first_keyword$item,
    imperfect = c(),
    explanation = "General explanation to the first situation"
  ),
  situation2 = base::list(
    interrogation = "Which of the following alternatives are associated to the second keyword?",
    correct = answer_group$second_keyword$item,
    explanation = "General explanation to the second situation"
  )
)

situation <- base::sample(situations, 1)

exercise <- teachR::questions_create_alternatives(
  feedbacks = feedbacks,
  codes = "QXXXXXXXXX",
  langiso = "US",
  situation = situation,
  altnbr = prm$altnbr,
  correctnbr = 1
)
if (base::sum(exercise$correct) == 1) {
  sormchoice <- "schoice"
  schoice <- TRUE
} else {
  sormchoice <- "mchoice"
  schoice <- FALSE
}
```



Question
========
`r prm$show_version` `r exercise$interrogation[[1]]` `r prm$show_points`

```{r question, echo = FALSE, results = "asis"}
exams::answerlist(exercise$proposition, markup = "markdown")
```



Solution
========

`r situation[[1]]$explanation`

```{r solution, echo = FALSE, results = "asis"}
teachR::questions_record_version(prm$record_version, prm$test, versionid, exercise)
exams::answerlist(
  ifelse(exercise$value, "Correct", "Incorrect"),
  exercise$explanation, markup = "markdown"
)
```



Meta-information
================
exname: `r versionid`  
extype: `r sormchoice`  
exsolution: `r exams::mchoice2string(exercise$correct, single = schoice)`  
exextra[title]:Title of the question.  
exextra[type]:Alternatives  
exextra[document]:  
exextra[tag_custom]:  
