```{r preparation, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
versionid <- "QXXXXXXXXX_US.Rmd"
prm <- teachR::questions_set_parameters(versionid, test_parameters, as_latex, record_version)
base::set.seed(prm$seed)

interrogation <- "Question asked to the student?"

right1 <- 1+0
error1 <- 2+0
error2 <- 3+0
error3 <- 4+0
error4 <- 5+0
error5 <- 6+0

exercise <- teachR::questions_create_computation(
  feedbacks = feedbacks,
  codes = "QXXXXXXXXX",
  langiso = "US",
  altnbr = prm$altnbr,
  interrogation = interrogation
) |>
  dplyr::mutate(proposition = purrr::map_chr(proposition, teachR::questions_prepare_evaluation)) |>
  dplyr::mutate(proposition = purrr::map_dbl(
    proposition,
    function(x) base::eval(base::parse(text = x))
  ))

if (prm$altnbr > 1) {
  exercise <- exercise |>
  dplyr::mutate(proposition = base::paste0(
    "The correct number is ", teachR::dbl(proposition),".")
  )
  schoiceornum <- "schoice"
  compsolution <- exams::mchoice2string(exercise$correct, single = TRUE)
} else {
  schoiceornum <- "num"
  compsolution <- right1
}
```



Question
========
`r prm$show_version` Story and data.

`r interrogation` `r prm$show_points`

```{r question, echo = FALSE, results = "asis"}
if (prm$altnbr > 1) exams::answerlist(exercise$proposition, markup = "markdown")
```



Solution
========

Explanation and solution.

```{r solution, echo = FALSE, results = "asis"}
teachR::questions_record_version(prm$record_version, prm$test, versionid, exercise)
exams::answerlist(
  ifelse(exercise$value, "This answer is right", "This answer is wrong"),
  exercise$explanation, markup = "markdown"
)
```


Meta-information
================
exname: `r versionid`  
extype: `r schoiceornum`  
exsolution: `r compsolution`  
exextra[title]:Title of the question.  
exextra[type]:Computation  
exextra[document]:  
exextra[tag_custom]:  
