```{r preparation, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
versionid <- "QXXXXXXXXX_US.Rmd"
prm <- teachR::questions_set_parameters(versionid, test_parameters, as_latex, record_version)
base::set.seed(prm$seed)

interrogation <- "Question asked to the student? (XX words)"

exercise <- teachR::questions_create_essay(
  feedbacks = feedbacks,
  codes = "QXXXXXXXXX",
  langiso = "US",
  interrogation = interrogation
)
```



Question
========
`r prm$show_version` `r interrogation` `r prm$show_points`



Solution
========

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results='asis'}
teachR::questions_record_version(prm$record_version, prm$test, versionid, exercise)
base::writeLines(base::paste0(c("<p>", exercise$explanation,"</p>"), collapse ="</p><p>"))
```




Meta-information
================
exname: `r versionid`  
extype: string  
exsolution: `r paste(exercise$explanation, collapse = " ")`  
exextra[title]:Title of the question.  
exextra[type]:Essay  
exextra[document]:  
exextra[tag_custom]:  
